
/*Selektiert die Belegungen*/

SELECT
    FERIENWOHNUNGEN.WOHNUNGSID, FERIENWOHNUNGEN.BESCHREIBUNGSTEXT, ORTE.ORTSNAME,
    ADRESSEN.STRASSE, ADRESSEN.HAUSNUMMER
FROM
    BELEGUNGEN, FERIENWOHNUNGEN, ADRESSEN, ORTE, LAENDER
WHERE
    (FERIENWOHNUNGEN.WOHNUNGSID = BELEGUNGEN.WOHNUNGSID) AND
    (FERIENWOHNUNGEN.ADRESSID = ADRESSEN.ADRESSID) AND
    (ADRESSEN.ORTSID = ORTE.ORTSID) AND
    (ORTE.LAND = LAENDER.ISOCODE) AND
    (LAENDER.LANDESNAME = 'Frankreich')
HAVING
    COUNT(BELEGUNGEN.BELEGUNGSNR) > 1
GROUP BY FERIENWOHNUNGEN.WOHNUNGSID, FERIENWOHNUNGEN.BESCHREIBUNGSTEXT, ORTE.ORTSNAME,
    ADRESSEN.STRASSE, ADRESSEN.HAUSNUMMER
ORDER BY COUNT(BELEGUNGEN.BELEGUNGSNR)
;