ALTER SESSION SET NLS_DATE_FORMAT = 'DD.MM.YYYY';
SELECT
    FERIENWOHNUNGEN.WOHNUNGSID, FERIENWOHNUNGEN.BESCHREIBUNGSTEXT, ORTE.ORTSNAME, ADRESSEN.STRASSE, ADRESSEN.HAUSNUMMER,
    COUNT(BELEGUNGEN.BELEGUNGSNR) AS Anzahl_Belegungen
FROM
    FERIENWOHNUNGEN, ADRESSEN, ORTE, LAENDER, BELEGUNGEN
WHERE
    (BELEGUNGEN.VON >= '01.05.2016') AND
    (BELEGUNGEN.BIS <= '21.05.2016') AND
    (FERIENWOHNUNGEN.WOHNUNGSID = BELEGUNGEN.BELEGUNGSNR) AND
    (ADRESSEN.ADRESSID = FERIENWOHNUNGEN.ADRESSID) AND
    (Orte.ORTSID = ADRESSEN.ORTSID) AND
    (LAENDER.ISOCODE = Orte.LAND) AND
    (LAENDER.ISOCODE = 'TR')
GROUP BY FERIENWOHNUNGEN.WOHNUNGSID, FERIENWOHNUNGEN.BESCHREIBUNGSTEXT, ORTE.ORTSNAME, ADRESSEN.STRASSE, ADRESSEN.HAUSNUMMER
ORDER BY COUNT(BELEGUNGEN.BELEGUNGSNR);


/*Passt so noch nicht.*/