
/*Selektiert die Buchungen*/

SELECT
    FERIENWOHNUNGEN.WOHNUNGSID, FERIENWOHNUNGEN.BESCHREIBUNGSTEXT, ORTE.ORTSNAME,
    ADRESSEN.STRASSE, ADRESSEN.HAUSNUMMER
FROM
    BELEGUNGEN, FERIENWOHNUNGEN, ADRESSEN, ORTE, LAENDER
WHERE
    (FERIENWOHNUNGEN.WOHNUNGSID = BELEGUNGEN.WOHNUNGSID) AND
    (FERIENWOHNUNGEN.ADRESSID = ADRESSEN.ADRESSID) AND
    (ADRESSEN.ORTSID = ORTE.ORTSID) AND
    (ORTE.LAND = LAENDER.ISOCODE) AND
    (BELEGUNGEN.BUCHUNGSSTATUS = 'Buchung') AND
    (COUNT(Belegungen.BELEGUNGSNR) >= 1)
GROUP BY FERIENWOHNUNGEN.WOHNUNGSID
ORDER BY COUNT(BELEGUNGEN.BELEGUNGSNR)
;