DELETE FROM Rechnungen;
DELETE FROM Belegungen;
DELETE FROM Bilder;
DELETE FROM bietet;
DELETE FROM Zusatzaustattungen;
DELETE FROM Ferienwohnungen;
DELETE FROM Kunden;
DELETE FROM Bankverbindungen;
DELETE FROM kalkulierte_Distanz;
DELETE FROM wird_angeflogen;
DELETE FROM Fluggesellschaften;
ALTER TABLE Orte DISABLE CONSTRAINT FK_Orte_Flughafen;
DELETE FROM Flughaefen;
DELETE FROM Touristenattraktionen;
DELETE FROM Adressen;
DELETE FROM Orte;
ALTER TABLE Orte ENABLE CONSTRAINT FK_Orte_Flughafen;
DELETE FROM Laender;
COMMIT;